# prometheus.yml
global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'
        
scrape_configs:

    - job_name: 'app'
      metrics_path: /prometheus
      target_groups:
          - targets: ['prometheus-app:8080']
          
    - job_name: 'node-exporter'
      target_groups:
          - targets: ['node-exporter:9100']